/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Redemption {
  'user' : Principal,
  'timestamp' : Time,
  'pointsRedeemed' : bigint,
  'redemptionType' : RedemptionType,
}
export type RedemptionType = { 'money' : null } |
  { 'coupon' : string };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WasteSubmission {
  'pointsAwarded' : bigint,
  'wasteType' : WasteType,
  'aiVerified' : boolean,
  'user' : Principal,
  'timestamp' : Time,
  'quantityKg' : bigint,
}
export type WasteType = { 'metal' : null } |
  { 'organic' : null } |
  { 'plastic' : null } |
  { 'glass' : null } |
  { 'paper' : null } |
  { 'electronic' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPlatformStats' : ActorMethod<
    [],
    { 'totalWasteKg' : bigint, 'totalPointsAwarded' : bigint }
  >,
  'getUserHistory' : ActorMethod<
    [Principal],
    {
      'submissions' : Array<WasteSubmission>,
      'redemptions' : Array<Redemption>,
    }
  >,
  'getUserPoints' : ActorMethod<[Principal], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'redeemPoints' : ActorMethod<[bigint, RedemptionType], undefined>,
  'submitWaste' : ActorMethod<[WasteType, bigint], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];