/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const WasteType = IDL.Variant({
  'metal' : IDL.Null,
  'organic' : IDL.Null,
  'plastic' : IDL.Null,
  'glass' : IDL.Null,
  'paper' : IDL.Null,
  'electronic' : IDL.Null,
});
export const Time = IDL.Int;
export const WasteSubmission = IDL.Record({
  'pointsAwarded' : IDL.Nat,
  'wasteType' : WasteType,
  'aiVerified' : IDL.Bool,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'quantityKg' : IDL.Nat,
});
export const RedemptionType = IDL.Variant({
  'money' : IDL.Null,
  'coupon' : IDL.Text,
});
export const Redemption = IDL.Record({
  'user' : IDL.Principal,
  'timestamp' : Time,
  'pointsRedeemed' : IDL.Nat,
  'redemptionType' : RedemptionType,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPlatformStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalWasteKg' : IDL.Nat,
          'totalPointsAwarded' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserHistory' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'submissions' : IDL.Vec(WasteSubmission),
          'redemptions' : IDL.Vec(Redemption),
        }),
      ],
      ['query'],
    ),
  'getUserPoints' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'redeemPoints' : IDL.Func([IDL.Nat, RedemptionType], [], []),
  'submitWaste' : IDL.Func([WasteType, IDL.Nat], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const WasteType = IDL.Variant({
    'metal' : IDL.Null,
    'organic' : IDL.Null,
    'plastic' : IDL.Null,
    'glass' : IDL.Null,
    'paper' : IDL.Null,
    'electronic' : IDL.Null,
  });
  const Time = IDL.Int;
  const WasteSubmission = IDL.Record({
    'pointsAwarded' : IDL.Nat,
    'wasteType' : WasteType,
    'aiVerified' : IDL.Bool,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'quantityKg' : IDL.Nat,
  });
  const RedemptionType = IDL.Variant({
    'money' : IDL.Null,
    'coupon' : IDL.Text,
  });
  const Redemption = IDL.Record({
    'user' : IDL.Principal,
    'timestamp' : Time,
    'pointsRedeemed' : IDL.Nat,
    'redemptionType' : RedemptionType,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPlatformStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalWasteKg' : IDL.Nat,
            'totalPointsAwarded' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserHistory' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'submissions' : IDL.Vec(WasteSubmission),
            'redemptions' : IDL.Vec(Redemption),
          }),
        ],
        ['query'],
      ),
    'getUserPoints' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'redeemPoints' : IDL.Func([IDL.Nat, RedemptionType], [], []),
    'submitWaste' : IDL.Func([WasteType, IDL.Nat], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };