/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface http_header {
    value: string;
    name: string;
}
export interface WasteSubmission {
    pointsAwarded: bigint;
    wasteType: WasteType;
    aiVerified: boolean;
    user: Principal;
    timestamp: Time;
    quantityKg: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Redemption {
    user: Principal;
    timestamp: Time;
    pointsRedeemed: bigint;
    redemptionType: RedemptionType;
}
export type RedemptionType = {
    __kind__: "money";
    money: null;
} | {
    __kind__: "coupon";
    coupon: string;
};
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WasteType {
    metal = "metal",
    organic = "organic",
    plastic = "plastic",
    glass = "glass",
    paper = "paper",
    electronic = "electronic"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getPlatformStats(): Promise<{
        totalWasteKg: bigint;
        totalPointsAwarded: bigint;
    }>;
    getUserHistory(user: Principal): Promise<{
        submissions: Array<WasteSubmission>;
        redemptions: Array<Redemption>;
    }>;
    getUserPoints(user: Principal): Promise<bigint>;
    isCallerAdmin(): Promise<boolean>;
    redeemPoints(points: bigint, redemptionType: RedemptionType): Promise<void>;
    submitWaste(wasteType: WasteType, quantityKg: bigint): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { Redemption as _Redemption, RedemptionType as _RedemptionType, Time as _Time, UserRole as _UserRole, WasteSubmission as _WasteSubmission, WasteType as _WasteType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlatformStats(): Promise<{
        totalWasteKg: bigint;
        totalPointsAwarded: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformStats();
            return result;
        }
    }
    async getUserHistory(arg0: Principal): Promise<{
        submissions: Array<WasteSubmission>;
        redemptions: Array<Redemption>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserHistory(arg0);
                return from_candid_record_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserHistory(arg0);
            return from_candid_record_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPoints(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPoints(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPoints(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async redeemPoints(arg0: bigint, arg1: RedemptionType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.redeemPoints(arg0, to_candid_RedemptionType_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redeemPoints(arg0, to_candid_RedemptionType_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async submitWaste(arg0: WasteType, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitWaste(to_candid_WasteType_n18(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitWaste(to_candid_WasteType_n18(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_RedemptionType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RedemptionType): RedemptionType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Redemption_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Redemption): Redemption {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_WasteSubmission_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WasteSubmission): WasteSubmission {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_WasteType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WasteType): WasteType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: Principal;
    timestamp: _Time;
    pointsRedeemed: bigint;
    redemptionType: _RedemptionType;
}): {
    user: Principal;
    timestamp: Time;
    pointsRedeemed: bigint;
    redemptionType: RedemptionType;
} {
    return {
        user: value.user,
        timestamp: value.timestamp,
        pointsRedeemed: value.pointsRedeemed,
        redemptionType: from_candid_RedemptionType_n14(_uploadFile, _downloadFile, value.redemptionType)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    submissions: Array<_WasteSubmission>;
    redemptions: Array<_Redemption>;
}): {
    submissions: Array<WasteSubmission>;
    redemptions: Array<Redemption>;
} {
    return {
        submissions: from_candid_vec_n6(_uploadFile, _downloadFile, value.submissions),
        redemptions: from_candid_vec_n11(_uploadFile, _downloadFile, value.redemptions)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pointsAwarded: bigint;
    wasteType: _WasteType;
    aiVerified: boolean;
    user: Principal;
    timestamp: _Time;
    quantityKg: bigint;
}): {
    pointsAwarded: bigint;
    wasteType: WasteType;
    aiVerified: boolean;
    user: Principal;
    timestamp: Time;
    quantityKg: bigint;
} {
    return {
        pointsAwarded: value.pointsAwarded,
        wasteType: from_candid_WasteType_n9(_uploadFile, _downloadFile, value.wasteType),
        aiVerified: value.aiVerified,
        user: value.user,
        timestamp: value.timestamp,
        quantityKg: value.quantityKg
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    metal: null;
} | {
    organic: null;
} | {
    plastic: null;
} | {
    glass: null;
} | {
    paper: null;
} | {
    electronic: null;
}): WasteType {
    return "metal" in value ? WasteType.metal : "organic" in value ? WasteType.organic : "plastic" in value ? WasteType.plastic : "glass" in value ? WasteType.glass : "paper" in value ? WasteType.paper : "electronic" in value ? WasteType.electronic : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    money: null;
} | {
    coupon: string;
}): {
    __kind__: "money";
    money: null;
} | {
    __kind__: "coupon";
    coupon: string;
} {
    return "money" in value ? {
        __kind__: "money",
        money: value.money
    } : "coupon" in value ? {
        __kind__: "coupon",
        coupon: value.coupon
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Redemption>): Array<Redemption> {
    return value.map((x)=>from_candid_Redemption_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WasteSubmission>): Array<WasteSubmission> {
    return value.map((x)=>from_candid_WasteSubmission_n7(_uploadFile, _downloadFile, x));
}
function to_candid_RedemptionType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RedemptionType): _RedemptionType {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_WasteType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WasteType): _WasteType {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "money";
    money: null;
} | {
    __kind__: "coupon";
    coupon: string;
}): {
    money: null;
} | {
    coupon: string;
} {
    return value.__kind__ === "money" ? {
        money: value.money
    } : value.__kind__ === "coupon" ? {
        coupon: value.coupon
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WasteType): {
    metal: null;
} | {
    organic: null;
} | {
    plastic: null;
} | {
    glass: null;
} | {
    paper: null;
} | {
    electronic: null;
} {
    return value == WasteType.metal ? {
        metal: null
    } : value == WasteType.organic ? {
        organic: null
    } : value == WasteType.plastic ? {
        plastic: null
    } : value == WasteType.glass ? {
        glass: null
    } : value == WasteType.paper ? {
        paper: null
    } : value == WasteType.electronic ? {
        electronic: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
